import {
  Smartphone,
  Tablet,
  Cable,
  Watch,
  Tv,
  Microwave,
  Laptop,
  Camera,
  Gamepad2,
  Refrigerator,
  Keyboard,
  HardDrive,
  AirVent,
  WashingMachine,
  Sofa,
  BedDouble,
  Flower2,
  Armchair,
  Lamp,
  Shirt,
  ShoppingBag,
  Baby,
  Car,
  Bike,
  Wrench,
  Truck,
  BookOpen,
  Music,
  Palette,
  Utensils,
  Lightbulb,
  Dumbbell,
  Medal,
  Trophy,
  ToyBrick,
  Home,
  KeyRound,
  LandPlot,
  Building2,
  Store,
  Fish,
  Bone,
  Dog,
  PawPrint,
  GraduationCap,
  Plane,
  HeartPulse,
  Hammer,
  SprayCan,
  Scale,
  Briefcase,
  Tag,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  // Mobiles & Tablets
  "Mobile Phones": Smartphone,
  Tablets: Tablet,
  Accessories: Cable,
  "Smart Watches": Watch,
  // Electronics
  "TVs, Video - Audio": Tv,
  "Kitchen & Other Appliances": Microwave,
  "Computers & Laptops": Laptop,
  "Cameras & Lenses": Camera,
  "Games & Entertainment": Gamepad2,
  Fridges: Refrigerator,
  "Computer Accessories": Keyboard,
  "Hard Disks, Printers & Monitors": HardDrive,
  ACs: AirVent,
  "Washing Machines": WashingMachine,
  // Furniture
  "Sofa & Dining": Sofa,
  "Beds & Wardrobes": BedDouble,
  "Home Decor & Garden": Flower2,
  "Kids Furniture": Armchair,
  "Other Household Items": Lamp,
  // Fashion
  Men: Shirt,
  Women: ShoppingBag,
  Kids: Baby,
  // Vehicles
  Cars: Car,
  Motorcycles: Bike,
  Scooters: Bike,
  Bicycles: Bike,
  "Spare Parts": Wrench,
  "Commercial & Other Vehicles": Truck,
  // Books & Hobbies
  Books: BookOpen,
  "Musical Instruments": Music,
  "Other Hobbies": Palette,
  // Home & Living
  Kitchenware: Utensils,
  Lighting: Lightbulb,
  // Sports & Fitness
  "Gym & Fitness": Dumbbell,
  "Sports Equipment": Medal,
  Cycling: Bike,
  "Other Sports": Trophy,
  // Kids & Baby
  Toys: ToyBrick,
  "Prams & Walkers": Baby,
  "Kids Clothing": Shirt,
  // Real Estate
  "For Sale: Houses & Apartments": Home,
  "For Rent: Houses & Apartments": KeyRound,
  "Lands & Plots": LandPlot,
  "For Sale: New Projects & Properties": Building2,
  "For Rent: Shops & Offices": Store,
  "For Sale: Shops & Offices": Store,
  "PG & Guest Houses": BedDouble,
  // Pet Supplies
  "Fishes & Aquarium": Fish,
  "Pet Food & Accessories": Bone,
  Dogs: Dog,
  "Other Pets": PawPrint,
  // Services
  "Education & Classes": GraduationCap,
  "Tours & Travel": Plane,
  "Electronics Repair & Services": Wrench,
  "Health & Beauty": HeartPulse,
  "Home Renovation & Repair": Hammer,
  "Cleaning & Pest Control": SprayCan,
  "Legal & Documentation Services": Scale,
  "Packers & Movers": Truck,
  "Other Services": Briefcase,
};

export function getSubcategoryIcon(name: string): LucideIcon {
  return icons[name] ?? Tag;
}
