import type { ChatMessage, Conversation } from "./chatTypes";

const p = (id: number) => `https://i.pravatar.cc/150?img=${id}`;

export const CURRENT_USER = {
  id: "me",
  name: "Carter Donin",
  role: "UI/UX Designer",
  avatar: "CD",
  photo: p(12),
  avatarColor: "#2f3adf",
};

export const initialConversations: Conversation[] = [
  {
    id: "c1",
    name: "Angel Franci",
    role: "Buyer",
    avatar: "AF",
    photo: p(5),
    avatarColor: "#F59E0B",
    lastMessage: "Voice message",
    lastMessageIcon: "mic",
    time: "5:29",
    unread: 0,
    pinned: true,
    online: true,
    verified: true,
  },
  {
    id: "c2",
    name: "Ace Kaylynn",
    role: "Buyer",
    avatar: "AK",
    photo: p(9),
    avatarColor: "#EC4899",
    lastMessage: "typing...",
    lastMessageIcon: "pen",
    time: "5:15",
    unread: 0,
    pinned: true,
    online: true,
    typing: true,
  },
  {
    id: "c3",
    name: "Craig Donin",
    role: "Buyer",
    avatar: "CR",
    photo: p(14),
    avatarColor: "#8B5CF6",
    lastMessage: "Ok, thanks!",
    time: "5:29",
    unread: 0,
    pinned: true,
    online: true,
    inCall: true,
    callDuration: "12m : 30s",
  },
  {
    id: "c4",
    name: "Allison Baptista",
    role: "Buyer",
    avatar: "AB",
    photo: p(20),
    avatarColor: "#10B981",
    lastMessage: "Is this still available?",
    time: "5:29",
    unread: 2,
    pinned: false,
    online: true,
  },
  {
    id: "c5",
    name: "Ruben Vetrovs",
    role: "Buyer",
    avatar: "RV",
    photo: p(15),
    avatarColor: "#F97316",
    lastMessage: "Uploads 7 photos...",
    lastMessageIcon: "image",
    time: "5:29",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: "c6",
    name: "Madelyn Philips",
    role: "Buyer",
    avatar: "MP",
    photo: p(47),
    avatarColor: "#06B6D4",
    lastMessage: "Sent an offer",
    lastMessageIcon: "offer",
    time: "5:29",
    unread: 3,
    pinned: false,
    online: true,
  },
  {
    id: "c7",
    name: "Kadin Botosh",
    role: "Buyer",
    avatar: "KB",
    photo: p(11),
    avatarColor: "#6366F1",
    lastMessage: "Where can we meet?",
    time: "5:29",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: "c8",
    name: "Roger Saris",
    role: "Buyer",
    avatar: "RS",
    photo: p(68),
    avatarColor: "#EF4444",
    lastMessage: "Perfect, see you then",
    time: "5:29",
    unread: 0,
    pinned: false,
    online: true,
  },
];

export const initialMessages: Record<string, ChatMessage[]> = {
  c1: [
    {
      id: "m1",
      conversationId: "c1",
      senderId: "c1",
      senderName: "Angel Franci",
      kind: "text",
      text: "Hey! Love the listing photos — is the item still available?",
      time: "4:52 PM",
      isMine: false,
      reactions: [
        { emoji: "👍", count: 1 },
        { emoji: "😍", count: 1 },
      ],
    },
    {
      id: "m2",
      conversationId: "c1",
      senderId: "system",
      kind: "text",
      text: "",
      time: "",
      isMine: false,
      dateLabel: "Today, 8 July",
    },
    {
      id: "m3",
      conversationId: "c1",
      senderId: "c1",
      senderName: "Angel Franci",
      kind: "voice",
      voiceDuration: "02:12",
      time: "5:18 PM",
      isMine: false,
    },
    {
      id: "m4",
      conversationId: "c1",
      senderId: "c1",
      senderName: "Angel Franci",
      kind: "text",
      text: "Can you check if @Carter still has the box and charger?",
      time: "5:20 PM",
      isMine: false,
      mentions: ["Carter"],
    },
    {
      id: "m5",
      conversationId: "c1",
      senderId: "c1",
      senderName: "Angel Franci",
      kind: "images",
      images: [
        "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=400&fit=crop",
        "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=400&h=400&fit=crop",
      ],
      time: "5:21 PM",
      isMine: false,
      reactions: [
        { emoji: "❤️", count: 2 },
        { emoji: "😂", count: 1 },
      ],
    },
    {
      id: "m6",
      conversationId: "c1",
      senderId: "me",
      senderName: "You",
      kind: "text",
      text: "Super, we will definitely use!",
      time: "5:24 PM",
      isMine: true,
    },
    {
      id: "m7",
      conversationId: "c1",
      senderId: "me",
      senderName: "You",
      kind: "offer",
      time: "5:25 PM",
      isMine: true,
      offer: {
        title: "MacBook Pro 14\" M2",
        price: 125000,
        currency: "₹",
        image:
          "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=200&h=200&fit=crop",
        status: "pending",
      },
      text: "Offer to sell",
    },
  ],
  c2: [
    {
      id: "m8",
      conversationId: "c2",
      senderId: "c2",
      senderName: "Ace Kaylynn",
      kind: "text",
      text: "Hey, interested in your iPhone listing.",
      time: "5:10 PM",
      isMine: false,
    },
  ],
  c4: [
    {
      id: "m9",
      conversationId: "c4",
      senderId: "c4",
      senderName: "Allison Baptista",
      kind: "text",
      text: "Is this still available?",
      time: "5:28 PM",
      isMine: false,
    },
    {
      id: "m10",
      conversationId: "c4",
      senderId: "c4",
      senderName: "Allison Baptista",
      kind: "text",
      text: "Can I pick it up today?",
      time: "5:29 PM",
      isMine: false,
    },
  ],
  c6: [
    {
      id: "m11",
      conversationId: "c6",
      senderId: "me",
      kind: "offer",
      time: "5:20 PM",
      isMine: true,
      offer: {
        title: "Sony WH-1000XM5",
        price: 18999,
        currency: "₹",
        status: "pending",
      },
      text: "Offer to sell",
    },
  ],
};
